### ISSUE TITLE
Trying to create userspace development "home directories"

### ISSUE THREAD

**Issue by bitsofalex** [garywiz/chaperone-docker#1]
The chaplocal command failed stating that it did not find the run.sh file. I was running this on a Mac.

Thanks.

**Comment by garywiz** [comment]
Can you tell me what environment you are using on the Mac?  Boot2docker, or Kitematic? etc.   Any other information about your configuration would be very much appreciated.   I'll duplicate the problem and let you know how to make it work properly.

**Comment by garywiz** [comment]
I think I've fixed your problem, plus about a dozen others you would have run into had you continued.   It turns out that the way volume permissions are handled under OSX is.... well... unfortunate.  So, I've implemented a few new features, modified scripts, etc.  I've tested all of these images (baseimage, lamp, lemp, alpinebase, apache) under Kitematic on my Mac and they seem to work in all modes.

The new versions are also pushed to Dockerhub and are tagged :latest as well as :1.0.6-U14.  Make sure you pull the most recent versions before trying again.  You should delete your chaplocal script and fetch another one using `--task` as is documented in the "Try it out" section on the main page.   I am planning to do much more extensive documentation about how to use these images and all their features very soon.

I won't close this because I'd love to hear your feedback and make sure it is all working.

**Comment by bitsofalex** [comment]
Cool thanks. I will check it out and let you know. The problem was caused by mapping home in Mac as home folder isn't really the same as other unix environments.

**Comment by bitsofalex** [comment]
Works like a charm now. Will try and build my image from it and feedback to you if I come across any other issues. Thanks heaps.

**Comment by garywiz** [comment]
No worries, glad it's working for you.  I'll close this and just open new issues if you run into problems or have questions.   You should be able to find thorough documentation about the syntax and features of configuration files in the [Configuration File Documentation](http://garywiz.github.io/chaperone/ref/config.html).
