### ISSUE TITLE
user service failed to start

### ISSUE THREAD

**Issue by bitsofalex** [garywiz/chaperone-docker#2]
I tried to run an executable jar as a service using 200-userapp.conf sample.service and it failed to start with and error:
system startup cancelled due to error: sample.service failed on start-up with result '<ProcStatus exit_status=1>'

Any ideas or help will be great.

**Comment by garywiz** [comment]
You'll run into such things a lot while developing, and there are a variety of ways to debug it.

First, if you are using "chaplocal" (as I think you are), you should find information in the `var/log/syslog.log` file inside your apps directory on your host box.  That may contain some instant clues about why your service failed to start.

Next, you can do a few more things:
1.   You can start your container with `./run.sh --debug` which will force all console output to appear in more detail during startup.
2.   You can start your container with `./run.sh --ignore-failures` which will tell Chaperone to go ahead and continue startup even though a service has failed.  Then, you will have a prompt inside the container and can explore the file system (`sudo` will work without a password if you want to be root).
3.   You can combine the above of course.

One thing you said is that you were trying to start a "jar" file.  However, none of the provided images have the Java JDK installed.  That could be the problem as well, and if so I can give you advice or write a quick wiki page about the best way to add it to the image.

I hope that's enough to get you started.

**Comment by garywiz** [comment]
I'm in the process of creating a `chaperone-alpinejava` image which has Oracle 8 Java along with Chaperone, identical in all other ways to the one you are using.  Even if that's not what you need, _somebody_ might, so it's not a bad idea.

**Comment by bitsofalex** [comment]
Based on your hints I was able to determine my problem. It was because I was trying to connect to a database on localhost which obviously doesn't exist anymore. As to the java I manually added the jdk onto your baseimage and built an image from that. Because it is a single responsibility container I find that work quite well as I am only running a single java process within the container. Obviously a container that you can provide will be even better. I am also thinking of taking this container into production. Is there anything that come to your mind that I should do beforehand.

Thanks for the fantastic support on the product.

**Comment by bitsofalex** [comment]
Do you have  a timeframe of you alpinejava image? It would be great if it I can use it.

Thanks again.

**Comment by garywiz** [comment]
I expect it will be about 15 minutes, I'm doing the production builds now.

**Comment by bitsofalex** [comment]
Awesome!

**Comment by garywiz** [comment]
There is a new Alpine Linux image, not too big (210MB) that has Oracle Version 8 JDK/JRE built in with a little sample app.  It also includes Python 3.  There is a link on the main chaperone-docker page, and it's now available.   I'm keeping my fingers crossed!  Good luck!

**Comment by garywiz** [comment]
As far as your comment about production, these images are currently being used on a few production servers, but not many, so it is still "Beta" quality software, but so far has been doing well.   I would suggest reviewing the service configuration defaults to make sure everything is to your liking, and the rest really up to what you need.   The quick reference shows the defaults for any service configuration setting: http://garywiz.github.io/chaperone/ref/config-service.html#service-quick-reference

Any feedback is really appreciated, thank you for giving it a try.  I'm also curious how the Alpine Java image works out.  I chose Alpine to keep the image size down, as some Java images are more than 600MB and I figured a leaner image may be desirable.

One thing to keep in mind is that your application may run under any user, and for the most part if you follow the development model that should work without worries.   When you're developing, it runs under your own UID.  But, if you run it in production without attached storage, then it will run as user 'runapps'.

You can get a production-ready launcher script from any of these images by saying:

   `docker run -i --rm chapdev/chaperone-alpinejava --task get-launcher | sh`

It can often serve as a template.

**Comment by bitsofalex** [comment]
I have tested the new alpinejava image and used it to build another very simple image with just my jar file added. When it starts up it complains of the following missing file or directory. Any ideas?
exec: "/usr/local/bin/chaperone": stat /usr/local/bin/chaperone: no such file or directory

**Comment by garywiz** [comment]
Hmm.  That is pretty odd.  The image is automatically tested before upload, and that just sounds weird.  I will look at it immediately and download the image from Docker Hub to see if it's different than the local one.

**Comment by bitsofalex** [comment]
It looks like chaperone is missing from the image.... I did a run.sh in to launch into the image and did an ls in the /usr/local/bin dir

---

NOTE: This is output from /Users/alex/dev/installs/chap/changeup/java_sample/SampleApp.class
      (A Java user application sample.)

You can disable this application, or replace it with your own by examining
the /Users/alex/dev/installs/chap/changeup/chaperone.d/200-userapp.conf configuration file.

Your container is running as user 'alex'.  This most likely means that your
application directory is shared with your host for easy development.

You're running interactively, but there is no console application.  Perhaps
you should add /bin/bash to the 'docker run' command line?

---

Aug 14 03:43:34 69a2366e2609 chaperone[1]: system will be killed when '/bin/bash' exits

Now running inside container. Directory is: /Users/alex/dev/installs/chap/changeup

bash-4.3$ cd /usr/local/
bash-4.3$ cd bin/
bash-4.3$ ls
bash-4.3$ ls -al
total 8
drwxr-xr-x    2 root     root          4096 Jun 12 19:19 .
drwxr-xr-x    6 root     root          4096 Aug 14 02:44 ..
bash-4.3$

**Comment by garywiz** [comment]
In the alpinejava image, Chaperone is located at "/usr/bin/chaperone" because that is where Alpine's pip installs it.    Is it possible you're using files from a non-Alpine image that you created before?  (Note, I hang out in #docker on freenode a lot if you ever are there yourself.)  I'll make a note to add a symlink for Alpine just so it is in both places.

The output you have above looks correct.  The "system will be killed" message comes from Chaperone, so it must be installed.  I believe!

**Comment by garywiz** [comment]
Ahh.  I bet the default Dockerfile doesn't cater to /usr/bin/chaperone and has /usr/local/bin/chaperone hardcoded.  I'll find the right fix for that now.  But, this would be something that would affect a derivative image build.

**Comment by bitsofalex** [comment]
Oh ok.... what should be entrypoint for the dockerfile then.... I see my problem

**Comment by garywiz** [comment]
I think it would be best if it were consistently `/usr/local/bin/chaperone`, so I am in the process of creating symlinks right now in the Alpine images.  If you can wait 15 mins, I'll push new ones.

**Comment by bitsofalex** [comment]
Of course.... That actually fixed it.... Awesome....

**Comment by garywiz** [comment]
I just tested and repushed the alpinebase and alpinejava images.  The ENTRYPOINT is now consistently `/usr/local/bin/chaperone`.   One small warning:  when you use `chaplocal` to create development directories, some of the items in the container are built using templates (you can see these in `etc/skel`).  So, if you switch from one image type to another, there may be some minor differences.

**Comment by bitsofalex** [comment]
It's working perfect now. Thanks heaps.

**Comment by bitsofalex** [comment]
Which user is the java service run as? I understand it is not root. Are there anything I have to do to create a service user for the app? Thanks again.

**Comment by garywiz** [comment]
The container setup is designed to set-up the user for you.  Although you can change it, I think it probably will work best the way it is.  Here is how it works:

By default, the [alpinebase Dockerfile](https://github.com/garywiz/chaperone-docker/blob/master/alpinebase/Dockerfile) specifies the following environment variable:
   `_CHAP_OPTIONS="--config apps/chaperone.d --default-home / --user runapps"`

That tells Chaperone to use that user for all services by default, and all built-in scripts (such as the provided `build/install.sh` script) assure that files copied into the container are owned by `runapps`.

However, when you run your image in development mode, using `chaplocal`, the `docker` command in `run.sh` overrides this in a way similar to the following:

  `docker run -i -t chapdev/chaperone-alpinejava --create-user alex:/Users/alex/dev/installs/chap/changeup/chaperone.d /bin/bash`

What this does is tell Chaperone to _create_ a brand new user inside the container called `alex` with the UID/GID credentials that are the same as the `chaperone.d` directory (whatever they are).  This is a clever way to get the container to "mimic" the user account credentials on your local system so that everything works fine.

In production, you often will want to do the same thing with attached storage.  The build assumes that the _only_ writes will occur to `/apps/var`, so in production scenarios the entire app is stored inside the container, but any persistent data is on attached storage.   Then, you can tell Chaperone to create a user to match the attached storage credentials:

  `docker run -v /mnt/persistent/myapp/var:/apps/var -d myapp-image --create-user produser:/apps/var`

The above command thus attaches persistent storage to the container's `/apps/var` directory, and also tells Chaperone to run all services as a newly-created user `produser` whose credentials will mimic those of the `/apps/var` mounted directory.  That way, your container services have full write access to attached storage without requiring root.

You can, using Chaperone's `uid` and `gid` service directives, specify that services run as any existing user on the system, including root, so you can override this on a per-service basis, or globally, but generally, that should be needed only for special cases.

Does this make sense to you?

**Comment by bitsofalex** [comment]
Yes. Thanks for the great support. Great work by the way.
